/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("VREPORTHObjectPageObjectPage journey");

        opaTest("Navigate to VREPORTHObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheVREPORTList.onFilterBar().iExecuteSearch();

            Then.onTheVREPORTList.onTable().iCheckRows();
            When.onTheVREPORTList.onTable().iPressRow(0);

            Then.onTheVREPORTObjectPage.iSeeThisPage();
            Then.onTheVREPORTObjectPage.onTable({ property: "_Vhead" }).iCheckRows();
            When.onTheVREPORTObjectPage.onTable({ property: "_Vhead" }).iPressRow(0);

            Then.onTheVREPORTHObjectPage.iSeeThisPage();
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheVREPORTHObjectPage.onHeader().iCheckHeaderFacet({ facetId: "VendorDetails" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheVREPORTHObjectPage.iCheckSection({ section: "HeadItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});